plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: ./plugin-push/bundles/@yarnpkg/plugin-push.js
    spec: "@yarnpkg/plugin-push"

yarnPath: .yarn/releases/yarn-2.2.2.cjs
